import os

# Resolved from the environment (env_var_resolver picks these up)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")

DATABASE_PASSWORD = "P@ssw0rd-EXAMPLE-not-real"
JWT_SIGNING_SECRET = "this_is_a_fake_signing_secret_EXAMPLE_1234567890"

AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

OPENAI_KEY_HARDCODED = "sk-proj-FAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEEXAMPLE"
SLACK_WEBHOOK = "https://hooks.slack.com/services/T00000000/B00000000/EXAMPLEEXAMPLE"
